services:
  - type: web
    name: sobreruedasec
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          - name: Cache-Control
            value: no-cache
    redirects:
      - source: /*
        destination: /index.html
        type: rewrite